# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_company_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(max_length=50)),
                ('col2', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Stack',
            new_name='UserStack',
        ),
    ]
